site_name: Ansible Lab
theme: flatly
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

nav:
- Introduction: 'index.md'
- Setup: 'setup/setup.md'
- Keys: 'keys/keys.md'
- Lab 1: 'lab-1/lab-1.md'
- Lab 2: 'lab-2/lab-2.md'
