---
- hosts: all
  become: yes
  gather_facts: no
  
  tasks:

  - name: install ntp
    apt:
      name: ntp
      state: present
      update_cache: yes

  - name: write our templated ntp.conf
    template:
      src: /home/vagrant/templates/ntp.conf.j2
      dest: /etc/ntp.conf
      mode: 0644
      owner: root
      group: root
    notify: restart ntp

  - name: start ntp
    service:
      name: ntp
      state: started

  handlers:

  - name: restart ntp
    service:
      name: ntp
      state: restarted
